### ISSUE TITLE
tpltexture？

### ISSUE THREAD

**Issue by toutheif** [NicholasMoser/GNTool#13]
Hello, my friend used your tool to export the TPL texture. After modification, some of them can't be repackaged into TPL. The color disk 256 exceeds the value。Or can you do a TPL matching export and import tool? I tried tplwii and wimms

**Comment by NicholasMoser** [comment]
Can you upload the modified texture as an attachment to this issue? I'll need it to verify any changes I do.

**Comment by NicholasMoser** [comment]
Also please let me know which texture it is replacing

**Comment by toutheif** [comment]
Hello, friend, I usually modify the texture of other Wii games and use brawlbox to modify the TPL file. I found that the TPL exported by your tool, as long as it is ci4, will prompt the color disk overflow, such as title / 0001 / 2.tpl, basically the value of rgb5a3 is invalid. You can try it

**Comment by NicholasMoser** [comment]
> After modification, some of them can't be repackaged into TPL.

Just so I understand, you're using BrawlBox right? You're right clicking and exporting:

![image](https://user-images.githubusercontent.com/4983605/93003355-a6c72f00-f503-11ea-90fb-54312ec63eaa.png)

Modifying the PNG and attempting to replace like so:

![image](https://user-images.githubusercontent.com/4983605/93003362-b9d9ff00-f503-11ea-9947-81417f3f84fe.png)

And getting an error like this?

![image](https://user-images.githubusercontent.com/4983605/93003382-d5450a00-f503-11ea-9876-93d0f1f81271.png)

GNTool uses [TXG2TPL](https://github.com/Struggleton/TXG2TPL) to convert the TXG files to TPL files. So if the issue is with the TPL itself, you'll likely want to log an issue against that repository. Or maybe this is an issue with BrawlBox? I'm honestly not sure, but I don't think there's anything GNTool can/should do about this.

**Comment by NicholasMoser** [comment]
May also be fixed by this PR? https://github.com/libertyernie/brawltools/pull/232
Looks like you'll need to build from source though.
