### ISSUE TITLE
Generic ISO Opener

### ISSUE THREAD

**Issue by mitchellhumphrey** [NicholasMoser/GNTool#5]
# Suggestion
add a generic 'can opener mode' that only opens games one way, and creates an uncompressed version of said game that can run on Dolphin

**Comment by NicholasMoser** [comment]
Since GNT4 requires specific code to unpack in a state Dolphin can run, I would assume any other game would require the same. If you send me a game and mod ready version of a game I can tell you whether that's true or not.

If it does require special code I can certainly add that as a specific game, I just don't know that I can make a can opener mode if every game requires its own specific file layout.
