### ISSUE TITLE
Player Priority

### ISSUE THREAD

**Issue by Super-GNT4** [NicholasMoser/GNTool#78]
It appears the game prioritizes players in a way which messes up many of the functions. In the vanilla basis of the game, Kabuto's Act2A applies the damage on frame 1. This is properly applied for player 1, but not for player 2. This also applies to the phantom sword glitch as well as grab breaks. This means (to me) that this works properly against player 2, but not against player 1 as the same thing applies with the grabs.

For throw breaks, when this applies to player 2 they are given the proper duration (3 in vanilla), but player 1 is given a reduced duration (2 in vanilla).

Would like to find a way to equalize this

**Comment by NicholasMoser** [comment]
To investigate this I decided to look into throw breaks specifically. Throw breaks give you 3 frames to react, which is implemented via a counter set to 0x300 and decrements by 0x100. For whatever reason, P1 only gets 2 frames to react. This is because it decrements **before** the first check.

```
P2 throw
--------
throw check P1
set counter to 0x300
throw check P2
throw check P1
decrement counter by 0x100
throw check P2
BREAK OPPORTUNITY!

P1 throw
--------
throw check P1
throw check P2
set counter to 0x300
throw check P1
BREAK OPPORTUNITY!
```

The original frame count is set in opcode op_2002
chr_updates happen in opcode op_240c, specifically 240c0400

There must be some weird ordering of instructions going on.

**Comment by NicholasMoser** [comment]
I have a fix for this that appears to be working:
https://github.com/NicholasMoser/Naruto-GNT-Modding/blob/master/gnt4/docs/guides/gecko_codes.md#remove-port-priority-on-throw-breaks-nick

Please note that this doesn't fix all port priority shenanigans, just throw break windows.
